export const REGIONS = {
  NORTH: "North",
  NORTHEAST: "Northeast",
  CENTRAL: "Central",
  EAST: "East",
  WEST: "West",
  SOUTH: "South",
};

export const PROVINCE_TO_REGION: Record<string, string> = {
  // North
  "Chiang Mai": REGIONS.NORTH,
  "Chiang Rai": REGIONS.NORTH,
  Lamphun: REGIONS.NORTH,
  Lampang: REGIONS.NORTH,
  Phrae: REGIONS.NORTH,
  Nan: REGIONS.NORTH,
  Phayao: REGIONS.NORTH,
  "Mae Hong Son": REGIONS.NORTH,
  Uttaradit: REGIONS.NORTH,

  // Northeast (Isan)
  "Nakhon Ratchasima": REGIONS.NORTHEAST,
  "Khon Kaen": REGIONS.NORTHEAST,
  "Ubon Ratchathani": REGIONS.NORTHEAST,
  "Udon Thani": REGIONS.NORTHEAST,
  Buriram: REGIONS.NORTHEAST,
  Sisaket: REGIONS.NORTHEAST,
  Surin: REGIONS.NORTHEAST,
  "Roi Et": REGIONS.NORTHEAST,
  Chaiyaphum: REGIONS.NORTHEAST,
  "Sakon Nakhon": REGIONS.NORTHEAST,
  "Nakhon Phanom": REGIONS.NORTHEAST,
  Loei: REGIONS.NORTHEAST,
  Kalasin: REGIONS.NORTHEAST,
  "Maha Sarakham": REGIONS.NORTHEAST,
  "Nong Khai": REGIONS.NORTHEAST,
  Mukdahan: REGIONS.NORTHEAST,
  Yasothon: REGIONS.NORTHEAST,
  "Amnat Charoen": REGIONS.NORTHEAST,
  "Nong Bua Lamphu": REGIONS.NORTHEAST,
  "Bueng Kan": REGIONS.NORTHEAST,

  // Central
  Bangkok: REGIONS.CENTRAL,
  "Samut Prakan": REGIONS.CENTRAL,
  Nonthaburi: REGIONS.CENTRAL,
  "Pathum Thani": REGIONS.CENTRAL,
  "Phra Nakhon Si Ayutthaya": REGIONS.CENTRAL,
  "Ang Thong": REGIONS.CENTRAL,
  Lopburi: REGIONS.CENTRAL,
  "Sing Buri": REGIONS.CENTRAL,
  "Chai Nat": REGIONS.CENTRAL,
  Saraburi: REGIONS.CENTRAL,
  "Nakhon Nayok": REGIONS.CENTRAL,
  "Nakhon Sawan": REGIONS.CENTRAL,
  "Uthai Thani": REGIONS.CENTRAL,
  "Kamphaeng Phet": REGIONS.CENTRAL,
  Sukhothai: REGIONS.CENTRAL,
  Phitsanulok: REGIONS.CENTRAL,
  Phichit: REGIONS.CENTRAL,
  Phetchabun: REGIONS.CENTRAL,
  "Suphan Buri": REGIONS.CENTRAL,
  "Nakhon Pathom": REGIONS.CENTRAL,
  "Samut Sakhon": REGIONS.CENTRAL,
  "Samut Songkhram": REGIONS.CENTRAL,

  // East
  Chonburi: REGIONS.EAST,
  Rayong: REGIONS.EAST,
  Chanthaburi: REGIONS.EAST,
  Trat: REGIONS.EAST,
  Chachoengsao: REGIONS.EAST,
  Prachinburi: REGIONS.EAST,
  "Sa Kaeo": REGIONS.EAST,

  // West
  Ratchaburi: REGIONS.WEST,
  Kanchanaburi: REGIONS.WEST,
  Tak: REGIONS.WEST,
  Phetchaburi: REGIONS.WEST,
  "Prachuap Khiri Khan": REGIONS.WEST,

  // South
  "Nakhon Si Thammarat": REGIONS.SOUTH,
  "Surat Thani": REGIONS.SOUTH,
  Songkhla: REGIONS.SOUTH,
  Phuket: REGIONS.SOUTH,
  Krabi: REGIONS.SOUTH,
  "Phang Nga": REGIONS.SOUTH,
  Ranong: REGIONS.SOUTH,
  Chumphon: REGIONS.SOUTH,
  Trang: REGIONS.SOUTH,
  Satun: REGIONS.SOUTH,
  Phatthalung: REGIONS.SOUTH,
  Pattani: REGIONS.SOUTH,
  Yala: REGIONS.SOUTH,
  Narathiwat: REGIONS.SOUTH,
};
